# Generated by Django 5.0.4 on 2024-04-19 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideosModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("file_name", models.CharField()),
                (
                    "requested_rover",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CUR", "curiosity"),
                            ("OPP", "opportunity"),
                            ("SPI", "spirit"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "requested_camera",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FHAZ", "Front Hazard Avoidance Camera"),
                            ("RHAZ", "Rear Hazard Avoidance Camera"),
                            ("MAST", "Mast Camera"),
                            ("CHEMCAM", "Chemistry and Camera Complex"),
                            ("MAHLI", "Mars Hand Lens Imager"),
                            ("MARDI", "Mars Descent Imager"),
                            ("NAVCAM", "Navigation Camera"),
                            ("PANCAM", "Panoramic Camera"),
                            (
                                "MINITES",
                                "Miniature Thermal Emission Spectrometer (Mini-TES)",
                            ),
                        ],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("is_done", models.BooleanField(blank=True, default=False)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mars Videos Request",
                "db_table": "videos_request",
            },
        ),
    ]
